@startuml

skinparam backgroundColor transparent

(*) --> P1
(*) --> P2
(*) --> P3
(*) --> P4
(*) --> P5
(*) --> P6
(*) --> P7

P1 --> N1
P1 --> N2
P1 --> N3
P1 --> N4
P1 --> N5
P1 --> N6
P1 --> N7

P2 ----> N8
P2 ----> N9
P2 ----> N10
P2 ----> N11
P2 ----> N12
P2 ----> N13
P2 ----> N14

P3 --> N15
P3 --> N16
P3 --> N17
P3 --> N18
P3 --> N19
P3 --> N20
P3 --> N21

P4 ----> N22
P4 ----> N23
P4 ----> N24
P4 ----> N25
P4 ----> N26
P4 ----> N27
P4 ----> N28

P5 --> N29
P5 --> N30
P5 --> N31
P5 --> N32
P5 --> N33
P5 --> N34
P5 --> N35

P6 ----> N36
P6 ----> N37
P6 ----> N38
P6 ----> N39
P6 ----> N40
P6 ----> N41
P6 ----> N42

P7 --> N43
P7 --> N44
P7 --> N45
P7 --> N46
P7 --> N47
P7 --> N48
P7 --> N49



@enduml
