@startuml

skinparam backgroundColor transparent

package P1 {
    agent N34
    agent N32
    agent N4
    agent N6
    agent N40
    agent N13
    agent N47
    agent N17
    agent N18
    agent N29
    agent N1
    agent N25
    agent N14
    agent N3
    agent N7
    agent N20
    agent N23
    agent N28
    agent N30
    agent N24
    agent N19
    agent N10
    agent N12
    agent N43
    agent N21
}
package P2 {
    agent N37
    agent N2
    agent N36
    agent N42
    agent N44
    agent N49
    agent N9
    agent N41
}
package P3 {
    agent N27
    agent N35
    agent N48
    agent N22
}
package P4 {
    agent N33
    agent N38
    agent N8
    agent N15
    agent N50
}
package P5 {
    agent N31
    agent N39
    agent N11
    agent N46
}
package P6 {
    agent N45
    agent N5
    agent N16
    agent N26
}

P1 -- P2
P2 -- P4
P1 -- P4
P1 -- P5
P1 -- P3
P2 -- P3
P1 -- P6
P3 -- P4
P2 -- P6
P2 -- P5

N4 -- N47
N23 -- N19
N37 -- N36
N10 -- N19
N13 -- N25
N19 -- N24
N36 -- N37
N18 -- N34
N17 -- N12
N36 -- N49
N10 -- N25
N24 -- N4
N36 -- N37
N14 -- N6
N35 -- N27
N30 -- N25
N46 -- N31
N50 -- N8
N33 -- N15
N34 -- N4
N38 -- N33
N34 -- N17
N42 -- N37
N18 -- N1
N28 -- N32
N40 -- N3
N12 -- N29
N45 -- N5
N34 -- N6
N37 -- N49
N24 -- N30
N7 -- N23
N32 -- N20
N6 -- N21
N1 -- N32
N40 -- N34
N13 -- N29
N17 -- N17
N30 -- N14
N2 -- N42
N27 -- N22
N47 -- N34
N6 -- N23
N44 -- N37
N13 -- N29
N13 -- N14
N32 -- N34
N39 -- N31
N39 -- N11
N19 -- N28
N3 -- N18
N50 -- N33
N8 -- N33
N4 -- N6
N40 -- N30
N16 -- N45
N17 -- N28
N34 -- N13
N32 -- N24
N25 -- N4
N40 -- N18
N9 -- N2
N26 -- N16
N21 -- N43
N10 -- N43
N47 -- N3
N31 -- N11
N13 -- N43
N28 -- N32
N19 -- N10
N20 -- N13
N15 -- N8
N7 -- N1
N2 -- N41
N10 -- N12
N2 -- N37
N26 -- N45
N44 -- N36
N34 -- N29
N7 -- N13
N27 -- N48
N43 -- N32

@enduml
